### ISSUE TITLE
Undefined index: global

### ISSUE THREAD

**Issue by sergeifilippov** [brettdewoody/statamic-global-variable-editor#1]
Installed the module and updated the `settings.yaml` as per the docs. Added the following to `theme.yaml`:

``` yaml
global:
  test: yes
```

The link shows on in admin, but when I click on it I get the following:

```
_add-ons/globes/tasks.globes.php
Exception:
  Undefined index: global
Line: 15
```

``` php
$globals = $settings['global'];
```

My setup:
- Statamic **1.8.4**
- Nginx  **1.6.2**
- PHP-FPM  **5.4.33**

Thought?

**Comment by brettdewoody** [comment]
Try to change `yes` to something else, like a number, or another word. Another option, wrap it in quotes like `'yes'`. Let me know if that fixes things.

**Comment by brettdewoody** [comment]
On second look, it appears it's not picking up the `global` array from the `theme.yaml` file. 

Does your `theme.yaml` file live at `_themes/[THEME_NAME]/theme.yaml`?

**Comment by sergeifilippov** [comment]
Good question, my theme files (including `theme.yaml`) live in `/assets`.

I've used the Jason Vargas method documented [here](https://pixelfear.com/blog/pretty-statamic-theme-urls) to achieve this.

I've tried it using the default Statamic folder structure and got the same result.

**Comment by brettdewoody** [comment]
Interesting, I hadn't seen that setup before. 

If you go with the default theme setup, and remove the theme path settings from `settings.yaml` does it work?

**Comment by sergeifilippov** [comment]
yeah done that also. same effect.

**Comment by brettdewoody** [comment]
What type of setup are you on?

**Comment by sergeifilippov** [comment]
My setup:
Laravel Homestead using Vagrant
Statamic **1.9.2**
Nginx **1.6.2**
PHP-FPM **5.6.4-1**

**Comment by brettdewoody** [comment]
Do the `global:tagname` variables work in your templates? 

For example if you put `{{ global: test }}` into a template does it display `yes`?

**Comment by brettdewoody** [comment]
@sergeifilippov Did you try the above? I'd love to get this resolved as I'm thinking of adding a few more features.

**Comment by sergeifilippov** [comment]
Yep that worked as I used `{{ global:test }}`

**Comment by brettdewoody** [comment]
Great, glad we resolved that. Thanks for following up.
