### ISSUE TITLE
I broke it?

### ISSUE THREAD

**Issue by iDGS** [brettdewoody/statamic-global-variable-editor#2]
Seems defining a global in the `theme.yaml` file or via the CP of [[a char or string of chars], [colon], [space], [more chars]], goes boom.

E.g., 

```
1, 2, 3: !
TESTING 1, 2, 3: !
TEST: !
T: !
Q: ?
Eh: What's up Doc?
```

all produce a slim error.

OTOH, swap in a semicolon, as e.g.,

```
Eh; What's up Doc?
```

and all is well.

I hate to say it, but it just might be time for a colon-oscopy! ;-D

But seriously, what to do?

**Comment by brettdewoody** [comment]
Great find, sounds like I need to escape some characters.

UPDATE: I copied and pasted your example array into my `theme.yaml` file and everything worked fine. The variables are displayed on my Constants page with the correct values. I'm using Statamic v1.9.2 so maybe it's a bit more forgiving than older versions. 

What version are you using?

**Comment by brettdewoody** [comment]
@iDGS Were you able to get this worked out? I'm thinking of adding some additional features and want to close the existing issues.  Let me know how it's going, thanks!

**Comment by iDGS** [comment]
Sorry for delay. I'll revisit this today and report back ASAP! (Saddles Rocinante, grabs helmet and lance... ;-)

**Comment by brettdewoody** [comment]
Going to close this issue as it's related to the new issue.

**Comment by iDGS** [comment]
Uh, it's your "car," but why, exactly? A flat tire and out of gas are both related to "it won't go," but they aren't necessarily the same problem. Me, I'd re-open this, because a Slim error--which I was on my way to dealing with when I got waylaid by "Huh. Why is that one item 'frozen'?"--is IMHO even more serious, and deserving of separate attention. (Thus, it's not that I'm negligent--but rather that I'm trying to be scrupulously thorough--that I've not yet gotten back here.)

**Comment by brettdewoody** [comment]
Reopened.

The variables you posted above worked for me. You would need to nest them in the `global` namespace however:

```
global:
  1, 2, 3: !
  TESTING 1, 2, 3: !
  TEST: !
  T: !
  Q: ?
  Eh: What's up Doc?
```

IMO, these are some extreme fringe cases. Global variables should be well-named - as single, camel-cased or underscore-delimited variable names. Variables names like `1, 2, 3` and other comma-delimited names shouldn't be used.

With the exception of the last variable I'm not super concerned with handling oddly named variables.  If that last variable:

```
global:
  Eh: What's up Doc?
```

doesn't work let me know and I can add some additional checks and escapes.

**Comment by iDGS** [comment]
Thanks for your patience. :-)

Good news: Yep, everything that used to go _kaboom_ now works fine. 

Specifically, I tried each one of these separately...

```
global:
  1, 2, 3: !
  TESTING 1, 2, 3: !
  TEST: !
  T: !
  Q: ?
  Eh: What's up Doc?
```

...appending each line one by one to the amended ReadMe example (see other issue #4, i.e., calling the `email` line `contact` instead), under Statamic 1.9.2 running inside localhost, and no Slim errors occurred. No errors of any kind occurred. In fact, it even worked just fine with the `theme.yaml` file open in BBEdit. Yay!

All of which I'm taking as solid evidence that you are a brilliant coder!

(So, "case closed!" ;-)

**Comment by brettdewoody** [comment]
Awesome, glad we got that resolved. Thanks for taking the time to help.
